# Generated by Django 2.2.13 on 2021-04-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210404_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='mike'),
            preserve_default=False,
        ),
    ]
