# Generated by Django 2.2.13 on 2021-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'Phones'), ('LW', 'Laptops'), ('G', 'Gadgets')], default='SW', max_length=2),
        ),
    ]
