# Generated by Django 2.2.13 on 2021-06-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210625_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category2',
            field=models.CharField(default='idle', max_length=20),
        ),
    ]
