# Generated by Django 2.2.13 on 2021-06-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
