# Generated by Django 2.2.13 on 2021-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210710_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flash',
            field=models.BooleanField(default=False),
        ),
    ]
